package Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import MyCode.DBconnect;
import MyCode.model;
import MyCode.products;
import com.lowagie.text.Phrase;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.xmlbeans.XmlErrorCodes;

import java.text.*;
import java.awt.print.*;
import javax.swing.table.TableModel;

/**
 *
 * @author qaisf
 */
public class stockentry extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form stockentry
     */
    public stockentry() {
        initComponents();
        con = DBconnect.connect();
        //con=dbcon.java_db();
        getid();
        getpay();
        getsum();
        showdate();
        getpaysum();
       
    }
    public String roll2,stid,date,spid,spnme,pid,pnme,paymethod;
    public static int ostk,kostk,chpay,cqpay;
    
   // public static int chqpay,cashpay;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void getid(){
        try {
            String sql="SELECT stockID FROM stock2 ORDER BY stockID DESC LIMIT 1";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                String rl=rs.getString("stockID");
                int ln=rl.length();
                String stxt=rl.substring(0,2);
                String snum=rl.substring(2,ln);
                int n=Integer.parseInt(snum);
                
                n++;
                snum=Integer.toString(n);
                String roll=stxt+snum;
                
                sidlable.setText(roll);
                
                
            }
            else{
                sidlable.setText("ST1001");
            }
        jLabel5.setOpaque(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }
    
    public int getsumpay(){
         int r=jTable2.getRowCount();
         int sum=0;
         for(int i=0;i<r;i++){
             sum=sum+Integer.parseInt(jTable2.getValueAt(i, 1).toString());
          //   jLabel12.setText(sum+"");
             
         }
         jLabel18.setText(sum+"");
         
         return sum;     
     }
     
     
     
     public void getpay(){
        try {
            String sql="SELECT paymentID FROM suppayments ORDER BY paymentID DESC LIMIT 1";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                String rl=rs.getString("paymentID");
                int ln=rl.length();
                String stxt=rl.substring(0,2);
                String snum=rl.substring(2,ln);
                int n=Integer.parseInt(snum);
                
                n++;
                snum=Integer.toString(n);
                 roll2=stxt+snum;
                
          
                
                
            }
            else{
                //jLabel10.setText("ST1001");
                roll2="PY1001";
            }
        //jLabel5.setOpaque(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"pay Error"+e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }
     
     public int getsum(){
         int r=jTable1.getRowCount();
         int sum=0;
         for(int i=0;i<r;i++){
             sum=sum+Integer.parseInt(jTable1.getValueAt(i, 4).toString());
          //   jLabel12.setText(sum+"");
             
         }
         jLabel12.setText(sum+"");
         
         return sum;    
     }
     
     
       public  int getpaysum(){
         int s=jTable3.getRowCount();
         int sum=0;
         for(int i=0;i<s;i++){
             sum=sum+Integer.parseInt(jTable3.getValueAt(i, 1).toString());
          //   jLabel12.setText(sum+"");
             
         }
         jLabel18.setText(sum+"");
         
         return sum;    
     }
     
     
     public void showdate(){
       Date dat=new Date();
       jDateChooser1.setDate(dat);
     }
     public stockentry(String msg){
         initComponents();
         this.pid=msg;
         jTextField4.setText(msg);
     }
    
     public void setnull(){
         jTextField2.setText("");
         jTextField1.setText("");
         jTextField10.setText("");
         jTextField5.setText("");
         jTextField4.setText("");
         jTextField6.setText("");
         jTextField7.setText("");
         jTextField11.setText("");
         jComboBox2.setSelectedIndex(0);
          jTable1.setModel(new DefaultTableModel(null,new String[]{"Product code","Product Name","Price","Qty","Total_Amount"}));
           jTable3.setModel(new DefaultTableModel(null,new String[]{"Payment_method","Amount"}));
     }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        sidlable = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2), "Payment Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel13.setText("Payment Method");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Payment Method", "Cash", "Card" }));

        jLabel14.setText("Payment");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "payment_method", "Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton17.setText("Add");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Remove");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 166, Short.MAX_VALUE)
                            .addComponent(jTextField9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuItem1.setText("Edit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Delete");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 728));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock Entry");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(418, 418, 418))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product code", "Product Name", "Price", "Qty", "Total_Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2), "Stock and Supplier Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setText("Stock ID");

        jLabel3.setText("Date");

        jLabel4.setText("Supplier ID");

        jLabel5.setText("Supplier Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        sidlable.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidlable)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sidlable))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2), "Product/Item Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel6.setText("Product Code");

        jLabel7.setText(" Name");

        jLabel8.setText("Quantity");

        jLabel9.setText("Price Per Unit");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel15.setText("Barcode");

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("GrandTotal");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("        0.00");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("           0.00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Total Payment");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2), "Payment Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel16.setText("Payment Method");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Payment");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "payment_method", "Amount"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton19.setText("Add");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Remove");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, 0, 166, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(35, 35, 35)
                                .addComponent(jTextField11)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jButton11.setText("New");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Save");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton15.setText("Close");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         
        try {
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
            String date=sdf.format(jDateChooser1.getDate());
            String sql="INSERT INTO suppayments VALUES(?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1,roll2);
            pst.setString(2,stid);
            pst.setString(3,date);
            pst.setString(4,spid);
            pst.setString(5,spnme);
            pst.setString(6,jLabel12.getText());
            pst.setInt(7,chpay);
            pst.setInt(8,cqpay);
            pst.execute();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"save Error:"+ e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        
        getid();
        getpay();
        
        
         String r1="";
        TableModel mod=jTable1.getModel();
       
        for(int i=0;i<jTable1.getRowCount();i++){
            r1=r1+String.valueOf(jTable1.getValueAt(i,0))+" "+String.valueOf(jTable1.getValueAt(i, 1))+" "+String.valueOf(jTable1.getValueAt(i, 2)+" "+String.valueOf(jTable1.getValueAt(i, 3))+" "+String.valueOf(jTable1.getValueAt(i, 4)))+"\n\n";
        }
        
          int  gt=Integer.parseInt(jLabel12.getText());
        int at=Integer.parseInt(jLabel12.getText());
        int ans=gt-at;
        String idate=jDateChooser1.getDate().toString();
         invoicearea n=new invoicearea();
         n.jTextArea1.setText("------------------------------\n"+
                "\t\tBeach Resort\t\t\n"+
                "------------------------------\n"+
                "\t077108397 /0525106038\t\n"+
                idate+"\t"+"Invoice ID:"+sidlable.getText()+"\t\n"+
                "------------------------------\n"+
                 "SupplierID:"+jTextField2.getText()+"\n"+
                 "SupplierName"+jTextField1.getText()+"\n"+
                 "--------------------------------\n"+
                "ItemId\t"+"ItemName\t"+"Price\t"+"Qty\t"+"Amount"+
                "-----------------------------\n"+
                r1+
                "-----------------------------\n"+
                "Gross Amount\t\t\t\t"+jLabel12.getText()+"\n"+
                "Cash\t\t\t"+jLabel18.getText()+"\n"+
                "------------------------------\n"+
                "Balance\t\t\t"+ans+"\n"+
                "========================================"+
                "\tThanknyou for your valued patronage!\t\n"+
                "=========================================");
        
           try {
            boolean com=n.jTextArea1.print();
            if(com)
            {
                JOptionPane.showMessageDialog(null,"done print");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"printing....");
            }
            
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
           setnull();
        
        
        /* MessageFormat header=new MessageFormat("Report Print");
        
         MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try {
            //jTable1.print(JTable.PrintMode.NORMAL, header, footer);
            jTable1.print(JTable.PrintMode.NORMAL, header, footer, rootPaneCheckingEnabled, null, rootPaneCheckingEnabled);
            
        } catch (Exception e) {
            System.out.println(e);
        }*/
        
        
        
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        main m=new main();
       // m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         // DefaultTableModel mod1=(DefaultTableModel) jTable1.getModel();
        
     //   String id=jTable1.getValueAt(r,0).toString();
       // jTextField3.setText(id);
       /* int r=jTable1.getSelectedRow();
        jTextField5.setText(jTable1.getValueAt(r,0).toString());
        jTextField4.setText(jTable1.getValueAt(r,1).toString());
        jTextField7.setText(jTable1.getValueAt(r,3).toString());        
        jTextField6.setText(jTable1.getValueAt(r,2).toString());*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod2=(DefaultTableModel) jTable1.getModel();
        int r=jTable1.getSelectedRow();
        
        String rpid,pnme;
        int ppu,qty,tot,pstt=0,prost=0,kst=0,krost=0;
        rpid=jTextField5.getText();
        pnme=jTextField4.getText();
        qty=Integer.parseInt(jTextField7.getText());
        ppu=Integer.parseInt(jTextField6.getText());
        
        tot=qty*ppu;
        
        String ln=rpid.substring(0,2);
        
        
         if(ln.equals("PD")){
        try {
            String sql="SELECT * FROM product WHERE productID='"+rpid+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                pstt=rs.getInt("optainstock");
                //rost=st+qty;
            }
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
             finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
        
        prost=pstt+qty;
        try{
            
            String u="UPDATE product SET optainstock='"+prost+"' WHERE productID='"+rpid+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        
        
        else if(ln.equals("KT")){
             try {
            String sql="SELECT * FROM kitchen WHERE itemID='"+rpid+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                kst=rs.getInt("optainstock");
               // kostk=st+qty;
            }
            }
              catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
             
             
           krost=kst+qty;  
             
             
             try{
            
            String u="UPDATE kitchen SET optainstock='"+krost+"' WHERE itemID='"+rpid+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        
        
        
        
        
        
    
      
        if(r>=0){
        mod2.setValueAt(pid, r, 0);
        mod2.setValueAt(pnme, r, 1);
        mod2.setValueAt(ppu, r, 2);
        mod2.setValueAt(qty, r, 3);
        mod2.setValueAt(tot, r, 4);
        }
        else{
            JOptionPane.showMessageDialog(null,"Error");
        }
        
        getsum();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              String bcod=jTextField10.getText();
              int sellprice=0;
              
        try {
            String s="SELECT * from WHERE barcode='"+bcod+"'";
            pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                spid=rs.getString("productID");
                spnme=rs.getString("productName");
                sellprice=rs.getInt("sellprice");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        jTextField5.setEditable(false);
        jTextField4.setEditable(false);
        
        jTextField5.setText(spid);
        jTextField4.setText(spnme);
        jTextField6.setText(sellprice+"");
        
        jTextField7.grabFocus();
            
        }
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // String stid,date,spid,spnme,pid,pnme;

        int tot,qty,ppu,st=0,osk=0,kst=0,st2=0;
        stid=sidlable.getText();
        spid=jTextField2.getText();
        spnme=jTextField1.getText();
       String pidp=jTextField5.getText();
        pnme=jTextField4.getText();
        qty=Integer.parseInt(jTextField7.getText());
        ppu=Integer.parseInt(jTextField6.getText());
        tot=qty*ppu;

        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        date=sdf.format(jDateChooser1.getDate());
        
        String ln=pidp.substring(0,2);
        
        

        try {
            String sql="INSERT INTO stock2 VALUES(?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1,stid);
            pst.setString(2,date);
            pst.setString(3,spid);
            pst.setString(4,spnme);
            pst.setString(5,pidp);
            pst.setString(6,pnme);
            pst.setInt(7,qty);
            pst.setInt(8,ppu);
            pst.execute();

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

        
        if(ln.equals("PD")){
        try {
            String sql="SELECT * FROM product WHERE productID='"+pidp+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                st=rs.getInt("optainstock");
                osk=st+qty;
            }
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
             finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
        
       // osk=st+qty;
        try{
            
            String u="UPDATE product SET optainstock='"+osk+"' WHERE productID='"+pidp+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        
        
        else if(ln.equals("KT")){
             try {
            String sql="SELECT * FROM kitchen WHERE itemID='"+pidp+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                st2=rs.getInt("optainstock");
               // kostk=st+qty;
            }
            }
              catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
             
             
           kst=st2+qty;  
             
             
             try{
            
            String u="UPDATE kitchen SET optainstock='"+kst+"' WHERE itemID='"+pidp+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
        mod.addRow(new Object[]{pidp,pnme,ppu,qty,tot});
        getsum();
        
        
        jTextField10.setText(null);
        jTextField5.setText(null);
        jTextField4.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField10.grabFocus();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        minsup s=new minsup();
        s.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              String pcod=jTextField5.getText();
        try {
            String s="SELECT * from product WHERE productID='"+pcod+"'";
            pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                spnme=rs.getString("productName");
                spnme=rs.getString("sellprice");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
       // jTextField5.setEditable(false);
        //jTextField4.setEditable(false);
        
        
        jTextField4.setText(spnme);
        jTextField6.setText(stid);
        
        jTextField6.grabFocus();
            
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              String pcod=jTextField2.getText();
        try {
            String s="SELECT * from supp WHERE supID='"+pcod+"'";
            pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                spid=rs.getString("supID");
                spnme=rs.getString("supname");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        
        jTextField2.setText(spid);
        jTextField1.setText(spnme);
        
        jTextField10.grabFocus();
       }
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            
        int tot,qty,ppu,st=0,osk=0,kst=0,st2=0;
        stid=sidlable.getText();
        spid=jTextField2.getText();
        spnme=jTextField1.getText();
       String pidp=jTextField5.getText();
        pnme=jTextField4.getText();
        qty=Integer.parseInt(jTextField7.getText());
        ppu=Integer.parseInt(jTextField6.getText());
        tot=qty*ppu;

        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        date=sdf.format(jDateChooser1.getDate());
        
        String ln=pidp.substring(0,2);
        
        

        try {
            String sql="INSERT INTO stock2 VALUES(?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1,stid);
            pst.setString(2,date);
            pst.setString(3,spid);
            pst.setString(4,spnme);
            pst.setString(5,pidp);
            pst.setString(6,pnme);
            pst.setInt(7,qty);
            pst.setInt(8,ppu);
            pst.execute();

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

        
        if(ln.equals("PD")){
        try {
            String sql="SELECT * FROM product WHERE productID='"+pidp+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                st=rs.getInt("optainstock");
                osk=st+qty;
            }
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
             finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
        
       // osk=st+qty;
        try{
            
            String u="UPDATE product SET optainstock='"+osk+"' WHERE productID='"+pidp+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        
        
        else if(ln.equals("KT")){
             try {
            String sql="SELECT * FROM kitchen WHERE itemID='"+pidp+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                st2=rs.getInt("optainstock");
               // kostk=st+qty;
            }
            }
              catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
             
             
           kst=st2+qty;  
             
             
             try{
            
            String u="UPDATE kitchen SET optainstock='"+kst+"' WHERE itemID='"+pidp+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
        mod.addRow(new Object[]{pidp,pnme,ppu,qty,tot});
        getsum();
        
        
        jTextField10.setText(null);
        jTextField5.setText(null);
        jTextField4.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField10.grabFocus();
 
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        stminpro sm=new stminpro();
        sm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
   /*     cpay=0;
        cdpay=0;

        paymeth=jComboBox1.getSelectedItem().toString();
        String pt=jTextField9.getText();
        if(paymeth=="cash"){
            cpay=Integer.parseInt(jTextField9.getText());

        }
        else if(paymeth=="card"){
            cdpay=Integer.parseInt(jTextField9.getText());
        }

        DefaultTableModel mod=(DefaultTableModel) jTable2.getModel();
        mod.addRow(new Object[]{paymeth,pt});*/

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        //chpay;
        //cqpay;

        paymethod=jComboBox2.getSelectedItem().toString();
       // if(paymeth=="Cheque"){
        //}
        String pt=jTextField11.getText();
        if(paymethod=="Cash"){
            chpay=Integer.parseInt(jTextField11.getText());

        }
        if(paymethod=="Cheque"){
            cqpay=Integer.parseInt(jTextField11.getText());
        }

        DefaultTableModel mod=(DefaultTableModel) jTable3.getModel();
        mod.addRow(new Object[]{paymethod,pt});
        getpaysum();
        jComboBox2.setSelectedItem("Choose Payment Method");
        jTextField11.setText(null);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedItem().toString()=="Cheque"){
            cheqpay ch=new cheqpay();
            ch.setVisible(true);
             
        }
       
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
         if(evt.isPopupTrigger()){
            jPopupMenu1.show(jTable1,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         int r=jTable1.getSelectedRow();
        jTextField5.setText(jTable1.getValueAt(r,0).toString());
        jTextField4.setText(jTable1.getValueAt(r,1).toString());
        jTextField6.setText(jTable1.getValueAt(r,2).toString());        
        jTextField7.setText(jTable1.getValueAt(r,3).toString());
        
        jButton3.setEnabled(false);
        
       int pro=Integer.parseInt(jTable1.getValueAt(r,3).toString());
       String pids=jTable1.getValueAt(r,0).toString();
       
       
        String ln=pids.substring(0,2);
        
        int rst=0,rost=0,krst=0,korst=0;
        
        
         if(ln.equals("PD")){
        try {
            String sql="SELECT * FROM product WHERE productID='"+pids+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                rst=rs.getInt("optainstock");
                //rost=st+qty;
            }
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
             finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
        
        rost=rst-pro;
        try{
            
            String u="UPDATE product SET optainstock='"+rost+"' WHERE productID='"+pids+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        
        
        else if(ln.equals("KT")){
             try {
            String sql="SELECT * FROM kitchen WHERE itemID='"+pids+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                krst=rs.getInt("optainstock");
               // kostk=st+qty;
            }
            }
              catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
             
             
           korst=krst-pro;  
             
             
             try{
            
            String u="UPDATE kitchen SET optainstock='"+korst+"' WHERE itemID='"+pids+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
       
       
       
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int r=jTable1.getSelectedRow();
           
       int pro=Integer.parseInt(jTable1.getValueAt(r,3).toString());
       String pids=jTable1.getValueAt(r,0).toString();
       
       
        String ln=pids.substring(0,2);
        
        int rst=0,rost=0,krst=0,korst=0;
        
        
         if(ln.equals("PD")){
        try {
            String sql="SELECT * FROM product WHERE productID='"+pids+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                rst=rs.getInt("optainstock");
                //rost=st+qty;
            }
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
             finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
        
        rost=rst-pro;
        try{
            
            String u="UPDATE product SET optainstock='"+rost+"' WHERE productID='"+pids+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
        
        
        
        else if(ln.equals("KT")){
             try {
            String sql="SELECT * FROM kitchen WHERE itemID='"+pids+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                krst=rs.getInt("optainstock");
               // kostk=st+qty;
            }
            }
              catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                  rs.close();
                  pst.close();
            } catch (Exception e) {
            }
        }
             
             
           korst=krst-pro;  
             
             
             try{
            
            String u="UPDATE kitchen SET optainstock='"+korst+"' WHERE itemID='"+pids+"'";
            pst=con.prepareStatement(u);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
            }
        }
         
         DefaultTableModel mod1=(DefaultTableModel) jTable1.getModel();
        int[] index=jTable1.getSelectedRows();
        
        for(int i=0;i<index.length;i++){
            mod1.removeRow(index[i]);
        }  
        
        getsum();
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        // TODO add your handling code here:
         String bcod=jTextField10.getText();
              int costprice=0;
              
        try {
            String s="SELECT * from product WHERE barcode='"+bcod+"'";
            pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                jTextField5.setText(rs.getString("productID"));
                jTextField4.setText(rs.getString("productName"));
                jTextField6.setText(rs.getInt("costprice")+"");
                jTextField6.grabFocus();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        jTextField5.setEditable(false);
        jTextField4.setEditable(false);
        
       // jTextField5.setText(spid);
        //jTextField4.setText(spnme);
        //jTextField6.setText(costprice+"");
        
       // jTextField7.grabFocus();
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        jTextField7.grabFocus();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        setnull();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        DefaultTableModel mod1=(DefaultTableModel) jTable3.getModel();
        int[] index=jTable3.getSelectedRows();
        
        for(int i=0;i<index.length;i++){
            mod1.removeRow(index[i]);
        }
        getsumpay();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        int enter = evt.getKeyChar();
    
        if(!(Character.isDigit(enter))) {
            
            jTextField7.setBackground(new Color(255, 102, 102));
            evt.consume();
            
        }

        else {
            
            jTextField7.setBackground(Color.WHITE);
            
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        int enter = evt.getKeyChar();
    
        if(!(Character.isDigit(enter))) {
            
            jTextField11.setBackground(new Color(255, 102, 102));
            evt.consume();
            
        }

        else {
            
            jTextField11.setBackground(Color.WHITE);
            
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockentry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField10;
    public static javax.swing.JTextField jTextField11;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    public static javax.swing.JLabel sidlable;
    // End of variables declaration//GEN-END:variables
}
